### ISSUE TITLE
Extra screens and navigation

### ISSUE THREAD

**Issue by thunderbiscuit** [ConorOkus/uMlando-wallet#9]
I'm wondering if you'd like to add a few extra screens with maybe a bottom nav bar to split up the features/buttons into separate locations or if maybe you're trying to keep this as simple as it gets on the UI side just to focus on the LDK part of the wallet.

Let me know, I can take a look and maybe PR a bit of navigation/screens if that's something you'd like to add.

**Comment by ConorOkus** [comment]
Yes this would be great, let's talk about the details next week!
